### ISSUE TITLE
How to get game id? 

### ISSUE THREAD

**Issue by pegasos1** [seemethere/nba_py#29]
How do you retrieve the game id for a particular game to supply to playbyplay and other functions?

**Comment by pegasos1** [comment]
Ah, realized i have to go through the `scoreboard` endpoint. However, continue to get 400 errors with the following: 

```
>>> from nba_py import game
>>> box = game.Boxscore('0041400122')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sgururangan/anaconda2/lib/python2.7/site-packages/nba_py/game.py", line 21, in __init__
    'EndRange': end_range})
  File "/home/sgururangan/anaconda2/lib/python2.7/site-packages/nba_py/__init__.py", line 42, in _get_json
    _get.raise_for_status()
  File "/home/sgururangan/anaconda2/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://stats.nba.com/stats/boxscore/?GameID=0041400122&RangeType=0&StartPeriod=0&StartRange=0&EndPeriod=0&EndRange=0
```
Also, 
```
>>> headers ={'referer': 'http://stats.nba.com/scores/', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0'}
>>> res = get('http://stats.nba.com/stats/scoreboard', params  = {'Date':'02/14/2015','LeagueID':00,'DayOffset':0}
>>> res
<Response [400]>
```

**Comment by pegasos1** [comment]
Going to close this issue, when pip installing latest version of nba__py, things work.
